version: 2
jobs:
  build:
    working_directory: ~/ruslingdk
    docker:
      - image: circleci/ruby:2.5.2-node
        environment:
          PG_HOST: localhost
          PG_USER: ubuntu
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: ruslingdk_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: ruslingdk-bundler-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: ruslingdk-bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 120s
      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run rspec in parallel
      - run: |
          bundle exec rspec
