OmniAuth.config.full_host = 'https://rusling.dk'

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :developer unless Rails.env.production?
  provider :github,   ENV.fetch('GITHUB_KEY', ''),   ENV.fetch('GITHUB_SECRET', ''), scope: 'user,user:email'
  provider :facebook, ENV.fetch('FACEBOOK_KEY', ''), ENV.fetch('FACEBOOK_SECRET', '')

  provider :saml,
    issuer: ENV.fetch('AAU_SAML_ISSUER', ''),
    idp_entity_id: "http://adfs.srv.aau.dk/adfs/services/trust",
    name_identifier_format: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
    idp_sso_target_url: "https://adfs.srv.aau.dk/adfs/ls/",
    idp_slo_target_url: "https://adfs.srv.aau.dk/adfs/ls/",
    idp_attribute_names: [
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn",
      "http://schemas.xmlsoap.org/claims/CommonName",
      "http://schemas.xmlsoap.org/claims/EmailAddress",
      "http://schemas.xmlsoap.org/claims/Group",
      "http://schemas.xmlsoap.org/claims/UPN",
      "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/privatepersonalidentifier",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
      "http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationinstant",
      "http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/denyonlysid",
      "http://schemas.microsoft.com/ws/2008/06/identity/claims/denyonlyprimarysid",
      "http://schemas.microsoft.com/ws/2008/06/identity/claims/denyonlyprimarygroupsid",
      "http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid",
      "http://schemas.microsoft.com/ws/2008/06/identity/claims/primarygroupsid",
      "http://schemas.microsoft.com/ws/2008/06/identity/claims/primarysid",
      "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname",
      "http://schemas.microsoft.com/2012/01/devicecontext/claims/isregistereduser",
      "http://schemas.microsoft.com/2012/01/devicecontext/claims/identifier",
      "http://schemas.microsoft.com/2012/01/devicecontext/claims/registrationid",
      "http://schemas.microsoft.com/2012/01/devicecontext/claims/displayname",
      "http://schemas.microsoft.com/2012/01/devicecontext/claims/ostype",
      "http://schemas.microsoft.com/2012/01/devicecontext/claims/osversion",
      "http://schemas.microsoft.com/2012/01/devicecontext/claims/ismanaged",
      "http://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-forwarded-client-ip",
      "http://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-client-application",
      "http://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-client-user-agent",
      "http://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-client-ip",
      "http://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-endpoint-absolute-path",
      "http://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-proxy",
      "http://schemas.microsoft.com/2012/01/requestcontext/claims/relyingpartytrustid",
      "http://schemas.microsoft.com/2012/12/certificatecontext/extension/applicationpolicy",
      "http://schemas.microsoft.com/2012/12/certificatecontext/extension/authoritykeyidentifier",
      "http://schemas.microsoft.com/2012/12/certificatecontext/extension/basicconstraints",
      "http://schemas.microsoft.com/2012/12/certificatecontext/extension/eku",
      "http://schemas.microsoft.com/2012/12/certificatecontext/field/issuer",
      "http://schemas.microsoft.com/2012/12/certificatecontext/field/issuername",
      "http://schemas.microsoft.com/2012/12/certificatecontext/extension/keyusage",
      "http://schemas.microsoft.com/2012/12/certificatecontext/field/notafter",
      "http://schemas.microsoft.com/2012/12/certificatecontext/field/notbefore",
      "http://schemas.microsoft.com/2012/12/certificatecontext/extension/certificatepolicy",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/rsa",
      "http://schemas.microsoft.com/2012/12/certificatecontext/field/rawdata",
      "http://schemas.microsoft.com/2012/12/certificatecontext/extension/san",
      "http://schemas.microsoft.com/ws/2008/06/identity/claims/serialnumber",
      "http://schemas.microsoft.com/2012/12/certificatecontext/field/signaturealgorithm",
      "http://schemas.microsoft.com/2012/12/certificatecontext/field/subject",
      "http://schemas.microsoft.com/2012/12/certificatecontext/extension/subjectkeyidentifier",
      "http://schemas.microsoft.com/2012/12/certificatecontext/field/subjectname",
      "http://schemas.microsoft.com/2012/12/certificatecontext/extension/certificatetemplateinformation",
      "http://schemas.microsoft.com/2012/12/certificatecontext/extension/certificatetemplatename",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/thumbprint",
      "http://schemas.microsoft.com/2012/12/certificatecontext/field/x509version",
      "http://schemas.microsoft.com/ws/2012/01/insidecorporatenetwork",
      "http://schemas.microsoft.com/ws/2012/01/passwordexpirationtime",
      "http://schemas.microsoft.com/ws/2012/01/passwordexpirationdays",
      "http://schemas.microsoft.com/ws/2012/01/passwordchangeurl",
      "http://schemas.microsoft.com/claims/authnmethodsreferences",
      "http://schemas.microsoft.com/2012/01/requestcontext/claims/client-request-id",
      "http://claims.aau.dk/2018/01/identity/claims/aauUserClassification",
      "urn:oid:2.5.4.4",
      "urn:oid:2.5.4.3",
      "urn:oid:0.9.2342.19200300.100.1.1",
      "urn:oid:0.9.2342.19200300.100.1.3",
      "dk:gov:saml:attribute:AssuranceLevel",
      "dk:gov:saml:attribute:SpecVer",
      "dk:gov:saml:attribute:CvrNumberIdentifier",
      "dk:gov:saml:attribute:UniqueAccountKey",
      "urn:oid:2.5.4.5",
      "urn:oid:2.5.4.10",
      "urn:oid:2.5.4.11",
      "urn:oid:2.5.4.12",
      "urn:oid:2.5.4.16",
      "urn:oid:2.5.4.65",
      "dk:gov:saml:attribute:IsYouthCert",
      "dk:gov:saml:attribute:PidNumberIdentifier",
      "dk:gov:saml:attribute:CprNumberIdentifier",
      "dk:gov:saml:attribute:RidNumberIdentifier",
      "http://www.ski.dk/eANnumber",
      "http://www.ski.dk/organizationNumber",
      "http://www.ski.dk/userPrincipalName",
      "http://www.ski.dk/givenName",
      "http://www.ski.dk/postalAddress",
      "http://www.ski.dk/l",
      "http://www.ski.dk/postalCode",
      "http://www.ski.dk/telephoneNumber",
      "http://www.ski.dk/mobile",
      "http://www.ski.dk/objectGUID",
      "http://www.ski.dk/whenCreated",
      "http://www.ski.dk/PNumberIdentifier",
      "http://www.ski.dk/roles",
      "http://www.ski.dk/udsteder"
    ],
    idp_cert: nil,
    idp_cert_fingerprint: nil,
    idp_cert_multi: {
      signing: [ENV.fetch('AAU_SAML_CERT_SIGN', '')],
      encryption: [ENV.fetch('AAU_SAML_CERT_ENCR', '')]
    }
end
